// playgrounds/vue/src/components/popover/popover.vue
<template>
  <div class="flex items-center justify-center space-x-12 p-12">
    <button>Previous</button>

    <PopoverGroup as="nav" ar-label="Mythical University" class="flex space-x-3">
      <Popover as="div" class="relative">
        <transition
          enter-active-class="transition ease-out duration-300 transform"
          enter-from-class="opacity-0"
          enter-to-class="opacity-100"
          leave-active-class="transition ease-in duration-300 transform"
          leave-from-class="opacity-100"
          leave-to-class="opacity-0"
        >
          <PopoverOverlay class="fixed inset-0 z-20 bg-gray-500 bg-opacity-75"></PopoverOverlay>
        </transition>

        <PopoverButton
          class="focus:outline-hidden relative z-30 border-2 border-transparent bg-gray-300 px-3 py-2 focus:border-blue-900"
        >
          Normal</PopoverButton
        >
        <PopoverPanel class="absolute z-30 flex w-64 flex-col border-2 border-blue-900 bg-gray-100">
          <button
            v-for="(link, i) of links"
            :key="i"
            :hidden="i === 2"
            class="focus:outline-hidden border-2 border-transparent px-3 py-2 text-left hover:bg-gray-200 focus:border-blue-900 focus:bg-gray-200"
          >
            Normal - {{ link }}
          </button>
        </PopoverPanel>
      </Popover>

      <Popover as="div" class="relative">
        <PopoverButton
          class="focus:outline-hidden border-2 border-transparent bg-gray-300 px-3 py-2 focus:border-blue-900"
          >Focus
        </PopoverButton>
        <PopoverPanel
          focus
          class="absolute flex w-64 flex-col border-2 border-blue-900 bg-gray-100"
        >
          <button
            v-for="(link, i) of links"
            :key="i"
            class="focus:outline-hidden border-2 border-transparent px-3 py-2 text-left hover:bg-gray-200 focus:border-blue-900 focus:bg-gray-200"
          >
            Focus - {{ link }}
          </button>
        </PopoverPanel>
      </Popover>

      <Popover as="div" class="relative">
        <PopoverButton
          ref="trigger1"
          class="focus:outline-hidden border-2 border-transparent bg-gray-300 px-3 py-2 focus:border-blue-900"
          >Portal
        </PopoverButton>
        <Portal>
          <PopoverPanel
            ref="container1"
            class="flex w-64 flex-col border-2 border-blue-900 bg-gray-100"
          >
            <button
              v-for="(link, i) of links"
              :key="i"
              class="focus:outline-hidden border-2 border-transparent px-3 py-2 text-left hover:bg-gray-200 focus:border-blue-900 focus:bg-gray-200"
            >
              Portal - {{ link }}
            </button>
          </PopoverPanel>
        </Portal>
      </Popover>

      <Popover as="div" class="relative">
        <PopoverButton
          ref="trigger2"
          class="focus:outline-hidden border-2 border-transparent bg-gray-300 px-3 py-2 focus:border-blue-900"
          >Focus in portal</PopoverButton
        >
        <Portal>
          <PopoverPanel
            ref="container2"
            focus
            class="flex w-64 flex-col border-2 border-blue-900 bg-gray-100"
          >
            <button
              v-for="(link, i) of links"
              :key="i"
              class="focus:outline-hidden border-2 border-transparent px-3 py-2 text-left hover:bg-gray-200 focus:border-blue-900 focus:bg-gray-200"
            >
              Focus in Portal - {{ link }}
            </button>
          </PopoverPanel>
        </Portal>
      </Popover>
    </PopoverGroup>

    <button>Next</button>
  </div>
</template>

<script>
import { defineComponent } from 'vue'
import {
  Popover,
  PopoverOverlay,
  PopoverPanel,
  PopoverGroup,
  PopoverButton,
  Portal,
} from '@eslamdevui/vue'
import { usePopper } from '../../playground-utils/hooks/use-popper'

function html(templates) {
  return templates.join('')
}

export default {
  components: {
    Popover,
    PopoverPanel,
    PopoverOverlay,
    PopoverGroup,
    PopoverButton,
    Portal,
  },
  setup() {
    let links = ['First', 'Second', 'Third', 'Fourth']

    let [trigger1, container1] = usePopper({
      placement: 'bottom-start',
      strategy: 'fixed',
    })

    let [trigger2, container2] = usePopper({
      placement: 'bottom-start',
      strategy: 'fixed',
    })

    return { links, trigger1, container1, trigger2, container2 }
  },
}
</script>

// playgrounds/react/pages/popover/popover.tsx
import { Popover, Transition } from '@eslamdevui/react'
import React, { forwardRef } from 'react'
import { ExampleMenu } from '../menu/menu'

let Button = forwardRef(
  (props: React.ComponentProps<'button'>, ref: React.MutableRefObject<HTMLButtonElement>) => {
    return (
      <Popover.Button
        className="focus:outline-hidden border-2 border-transparent bg-gray-300 px-3 py-2 text-left focus:border-blue-900"
        {...props}
        ref={ref}
      />
    )
  }
)

export default function Home() {
  let items = ['First', 'Second', 'Third', 'Fourth']

  return (
    <div className="flex items-center justify-center space-x-12 p-12">
      <button>Previous</button>

      <Popover.Group as="nav" aria-label="Mythical University" className="flex space-x-3">
        <Popover as="div" className="relative">
          <Transition
            enter="transition ease-out duration-300 transform"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="transition ease-in duration-300 transform"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <Popover.Overlay className="fixed inset-0 z-20 bg-gray-500/75"></Popover.Overlay>
          </Transition>

          <Popover.Button className="focus:outline-hidden relative z-30 border-2 border-transparent bg-gray-300 px-3 py-2 focus:border-blue-900">
            Normal
          </Popover.Button>
          <Popover.Panel className="absolute z-30 flex w-64 flex-col border-2 border-blue-900 bg-gray-100">
            {items.map((item, i) => (
              <Button key={item} hidden={i === 2}>
                Normal - {item}
              </Button>
            ))}
            <div className="p-2">
              <ExampleMenu />
            </div>
          </Popover.Panel>
        </Popover>

        <Popover as="div" className="relative">
          <Button>Focus</Button>
          <Popover.Panel
            focus
            className="absolute flex w-64 flex-col border-2 border-blue-900 bg-gray-100"
          >
            {items.map((item) => (
              <Button key={item}>Focus - {item}</Button>
            ))}
          </Popover.Panel>
        </Popover>

        <Popover as="div" className="relative">
          <Button>Portal</Button>
          <Popover.Panel
            anchor="bottom start"
            className="flex w-64 flex-col border-2 border-blue-900 bg-gray-100 [--anchor-gap:--spacing(1)]"
          >
            {items.map((item) => (
              <Button key={item}>Portal - {item}</Button>
            ))}
            <div className="p-2">
              <ExampleMenu />
            </div>
          </Popover.Panel>
        </Popover>

        <Popover as="div" className="relative">
          <Button>Focus in Portal</Button>
          <Popover.Panel
            focus
            anchor="bottom start"
            className="flex w-64 flex-col border-2 border-blue-900 bg-gray-100 [--anchor-gap:--spacing(1)]"
          >
            {items.map((item) => (
              <Button key={item}>Focus in Portal - {item}</Button>
            ))}
          </Popover.Panel>
        </Popover>
      </Popover.Group>

      <button>Next</button>
    </div>
  )
}
