// playgrounds/vue/src/components/combobox/combobox-countries.vue
<script>
import { countries as allCountries } from '../../data'
import { ref, defineComponent, computed, onMounted, watch } from 'vue'
import {
  Combobox,
  ComboboxButton,
  ComboboxInput,
  ComboboxLabel,
  ComboboxOption,
  ComboboxOptions,
} from '@eslamdevui/vue'

export default defineComponent({
  components: {
    Combobox,
    ComboboxButton,
    ComboboxInput,
    ComboboxLabel,
    ComboboxOption,
    ComboboxOptions,
  },
  setup() {
    let query = ref('')
    let activeCountry = ref(allCountries[2]) // allCountries[Math.floor(Math.random() * allCountries.length)]
    let filteredCountries = computed(() => {
      return query.value === ''
        ? allCountries
        : allCountries.filter((country) => {
            return country.toLowerCase().includes(query.value.toLowerCase())
          })
    })

    // Choose a random country on mount
    onMounted(() => {
      activeCountry.value = allCountries[Math.floor(Math.random() * allCountries.length)]
    })

    watch(activeCountry, () => {
      query.value = ''
    })

    return {
      query,
      activeCountry,
      filteredCountries,
    }
  },
})
</script>

<template>
  <div class="flex h-full w-screen justify-center bg-gray-50 p-12">
    <div class="mx-auto w-full max-w-xs">
      <div class="py-8 font-mono text-xs">
        Selected country: {{ activeCountry?.name ?? 'Nothing yet' }}
      </div>
      <div class="space-y-1">
        <Combobox v-model="activeCountry" as="div">
          <ComboboxLabel class="block text-sm font-medium leading-5 text-gray-700">
            Assigned to
          </ComboboxLabel>

          <div class="relative">
            <span class="shadow-xs relative inline-flex flex-row overflow-hidden rounded-md border">
              <ComboboxInput
                @change="query = $event.target.value"
                class="outline-hidden border-none px-3 py-1"
              />
              <ComboboxButton
                class="focus:outline-hidden cursor-default border-l bg-gray-100 px-1 text-indigo-600"
              >
                <span class="pointer-events-none flex items-center px-2">
                  <svg
                    class="h-5 w-5 text-gray-400"
                    viewBox="0 0 20 20"
                    fill="none"
                    stroke="currentColor"
                  >
                    <path
                      d="M7 7l3-3 3 3m0 6l-3 3-3-3"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </span>
              </ComboboxButton>
            </span>

            <div class="absolute mt-1 w-full rounded-md bg-white shadow-lg">
              <ComboboxOptions
                class="shadow-2xs focus:outline-hidden max-h-60 overflow-auto rounded-md py-1 text-base leading-6 sm:text-sm sm:leading-5"
              >
                <ComboboxOption
                  v-for="country in filteredCountries"
                  :key="country"
                  :value="country"
                  v-slot="{ active, selected }"
                >
                  <div
                    :class="[
                      'focus:outline-hidden relative cursor-default select-none py-2 pl-3 pr-9',
                      active ? 'bg-indigo-600 text-white' : 'text-gray-900',
                    ]"
                  >
                    <span :class="['block truncate', selected ? 'font-semibold' : 'font-normal']">
                      {{ country }}
                    </span>
                    <span
                      v-if="selected"
                      :class="[
                        'absolute inset-y-0 right-0 flex items-center pr-4',
                        active ? 'text-white' : 'text-indigo-600',
                      ]"
                    >
                      <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path
                          fillRule="evenodd"
                          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                          clipRule="evenodd"
                        />
                      </svg>
                    </span>
                  </div>
                </ComboboxOption>
              </ComboboxOptions>
            </div>
          </div>
        </Combobox>
      </div>
    </div>
  </div>
</template>

// playgrounds/react/pages/combobox/combobox-countries.tsx
import { Combobox } from '@eslamdevui/react'
import { useEffect, useState } from 'react'

import { Button } from '../../components/button'
import { countries as allCountries } from '../../data'
import { classNames } from '../../utils/class-names'

function useDebounce<T>(value: T, delay: number) {
  let [debouncedValue, setDebouncedValue] = useState(value)
  useEffect(() => {
    let timer = setTimeout(() => setDebouncedValue(value), delay)
    return () => clearTimeout(timer)
  }, [value, delay])
  return debouncedValue
}
export default function Home() {
  let [query, setQuery] = useState('')
  let [activeCountry, setActiveCountry] = useState(allCountries[2])

  // Mimic delayed response from an API
  let actualQuery = useDebounce(query, 0 /* Change to higher value like 100 for testing purposes */)

  // Choose a random person on mount
  useEffect(() => {
    setActiveCountry(allCountries[Math.floor(Math.random() * allCountries.length)])
  }, [])

  let countries =
    actualQuery === ''
      ? allCountries
      : allCountries.filter((person) => person.toLowerCase().includes(actualQuery.toLowerCase()))

  return (
    <div className="flex h-full w-screen justify-center bg-gray-50 p-12">
      <div className="mx-auto w-full max-w-xs">
        <div className="py-8 font-mono text-xs">Selected country: {activeCountry}</div>
        <div className="space-y-1">
          <Combobox
            value={activeCountry}
            onChange={(value) => {
              setActiveCountry(value)
              setQuery('')
            }}
            as="div"
          >
            <Combobox.Label className="block text-sm font-medium leading-5 text-gray-700">
              Country
            </Combobox.Label>

            <div className="relative">
              <span className="shadow-xs relative inline-flex flex-row overflow-hidden rounded-md border">
                <Combobox.Input
                  onChange={(e) => setQuery(e.target.value)}
                  className="outline-hidden border-none px-3 py-1"
                />
                <Combobox.Button as={Button}>
                  <span className="pointer-events-none flex items-center px-2">
                    <svg
                      className="h-5 w-5 text-gray-400"
                      viewBox="0 0 20 20"
                      fill="none"
                      stroke="currentColor"
                    >
                      <path
                        d="M7 7l3-3 3 3m0 6l-3 3-3-3"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </span>
                </Combobox.Button>
              </span>

              <Combobox.Options
                transition
                anchor="bottom start"
                className="focus:outline-hidden data-closed:opacity-0 w-[calc(var(--input-width)+var(--button-width))] overflow-auto rounded-md bg-white py-1 text-base leading-6 shadow-lg transition duration-300 [--anchor-gap:--spacing(1)] [--anchor-max-height:--spacing(60)] sm:text-sm sm:leading-5"
              >
                {countries.map((country) => (
                  <Combobox.Option
                    key={country}
                    value={country}
                    className={({ active }) => {
                      return classNames(
                        'focus:outline-hidden relative cursor-default select-none py-2 pl-3 pr-9',
                        active ? 'bg-indigo-600 text-white' : 'text-gray-900'
                      )
                    }}
                  >
                    {({ active, selected }) => (
                      <>
                        <span
                          className={classNames(
                            'block truncate',
                            selected ? 'font-semibold' : 'font-normal'
                          )}
                        >
                          {country}
                        </span>
                        {selected && (
                          <span
                            className={classNames(
                              'absolute inset-y-0 right-0 flex items-center pr-4',
                              active ? 'text-white' : 'text-indigo-600'
                            )}
                          >
                            <svg className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                              <path
                                fillRule="evenodd"
                                d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                clipRule="evenodd"
                              />
                            </svg>
                          </span>
                        )}
                      </>
                    )}
                  </Combobox.Option>
                ))}
              </Combobox.Options>
            </div>
          </Combobox>
        </div>
      </div>
    </div>
  )
}
