// playgrounds/vue/src/components/menu/menu-with-transition-and-popper.vue
<template>
  <div class="flex h-full w-screen justify-center bg-gray-50 p-12">
    <div class="relative mt-64 inline-block text-left">
      <Menu>
        <span class="shadow-xs inline-flex rounded-md">
          <MenuButton
            ref="trigger"
            class="focus:shadow-outline-blue focus:outline-hidden inline-flex w-full justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium leading-5 text-gray-700 transition duration-150 ease-in-out hover:text-gray-500 focus:border-blue-300 active:bg-gray-50 active:text-gray-800"
          >
            <span>Options</span>
            <svg class="-mr-1 ml-2 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path
                fillRule="evenodd"
                d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                clipRule="evenodd"
              />
            </svg>
          </MenuButton>
        </span>

        <div ref="container" class="w-56">
          <transition
            enter-active-class="transition duration-100 ease-out"
            enter-from-class="transform scale-95 opacity-0"
            enter-to-class="transform scale-100 opacity-100"
            leave-active-class="transition duration-75 ease-out"
            leave-from-class="transform scale-100 opacity-100"
            leave-to-class="transform scale-95 opacity-0"
          >
            <MenuItems
              class="outline-hidden w-full divide-y divide-gray-100 rounded-md border border-gray-200 bg-white shadow-lg"
            >
              <div class="px-4 py-3">
                <p class="text-sm leading-5">Signed in as</p>
                <p class="truncate text-sm font-medium leading-5 text-gray-900">tom@example.com</p>
              </div>

              <div class="py-1">
                <MenuItem as="a" :className="resolveClass" href="#account-settings">
                  Account settings
                </MenuItem>
                <MenuItem v-slot="data">
                  <a href="#support" :class="resolveClass(data)">Support</a>
                </MenuItem>
                <MenuItem as="a" :className="resolveClass" disabled href="#new-feature">
                  New feature (soon)
                </MenuItem>
                <MenuItem as="a" :className="resolveClass" href="#license">License</MenuItem>
              </div>
              <div class="py-1">
                <MenuItem as="a" :className="resolveClass" href="#sign-out">Sign out</MenuItem>
              </div>
            </MenuItems>
          </transition>
        </div>
      </Menu>
    </div>
  </div>
</template>

<script>
import { defineComponent, h, ref, onMounted, watchEffect, watch } from 'vue'
import { Menu, MenuButton, MenuItems, MenuItem } from '@eslamdevui/vue'
import { usePopper } from '../../playground-utils/hooks/use-popper'

function classNames(...classes) {
  return classes.filter(Boolean).join(' ')
}

export default {
  components: { Menu, MenuButton, MenuItems, MenuItem },
  setup(props, context) {
    let [trigger, container] = usePopper({
      placement: 'bottom-end',
      strategy: 'fixed',
      modifiers: [{ name: 'offset', options: { offset: [0, 10] } }],
    })

    function resolveClass({ active, disabled }) {
      return classNames(
        'flex justify-between w-full px-4 py-2 text-sm leading-5 text-left',
        active ? 'bg-gray-100 text-gray-900' : 'text-gray-700',
        disabled && 'cursor-not-allowed opacity-50'
      )
    }

    return {
      trigger,
      container,
      resolveClass,
    }
  },
}
</script>

// playgrounds/react/pages/menu/menu-with-transition-and-popper.tsx
import { Menu, Transition } from '@eslamdevui/react'

import { Button } from '../../components/button'
import { classNames } from '../../utils/class-names'
import { usePopper } from '../../utils/hooks/use-popper'

export default function Home() {
  let [trigger, container] = usePopper({
    placement: 'bottom-end',
    strategy: 'fixed',
    modifiers: [{ name: 'offset', options: { offset: [0, 10] } }],
  })

  function resolveClass({ active, disabled }) {
    return classNames(
      'flex justify-between w-full px-4 py-2 text-sm leading-5 text-left',
      active ? 'bg-gray-100 text-gray-900' : 'text-gray-700',
      disabled && 'cursor-not-allowed opacity-50'
    )
  }

  return (
    <div className="flex h-full w-screen justify-center bg-gray-50 p-12">
      <div className="mt-64 inline-block text-left">
        <Menu>
          <span className="shadow-xs rounded-md">
            <Menu.Button ref={trigger} as={Button}>
              <span>Options</span>
              <svg className="-mr-1 ml-2 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path
                  fillRule="evenodd"
                  d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                  clipRule="evenodd"
                />
              </svg>
            </Menu.Button>
          </span>

          <div ref={container} className="w-56">
            <Transition
              enter="transition duration-100 ease-out"
              enterFrom="transform scale-95 opacity-0"
              enterTo="transform scale-100 opacity-100"
              leave="transition duration-75 ease-out"
              leaveFrom="transform scale-100 opacity-100"
              leaveTo="transform scale-95 opacity-0"
            >
              <Menu.Items className="outline-hidden divide-y divide-gray-100 rounded-md border border-gray-200 bg-white shadow-lg">
                <div className="px-4 py-3">
                  <p className="text-sm leading-5">Signed in as</p>
                  <p className="truncate text-sm font-medium leading-5 text-gray-900">
                    tom@example.com
                  </p>
                </div>

                <div className="py-1">
                  <Menu.Item as="a" href="#account-settings" className={resolveClass}>
                    Account settings
                  </Menu.Item>
                  <Menu.Item>
                    {(data) => (
                      <a href="#support" className={resolveClass(data)}>
                        Support
                      </a>
                    )}
                  </Menu.Item>
                  <Menu.Item as="a" disabled href="#new-feature" className={resolveClass}>
                    New feature (soon)
                  </Menu.Item>
                  <Menu.Item as="a" href="#license" className={resolveClass}>
                    License
                  </Menu.Item>
                </div>
                <div className="py-1">
                  <Menu.Item as="a" href="#sign-out" className={resolveClass}>
                    Sign out
                  </Menu.Item>
                </div>
              </Menu.Items>
            </Transition>
          </div>
        </Menu>
      </div>
    </div>
  )
}
